### ISSUE TITLE
Переделать на test.each

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-exercise1.horoscope#1]
https://github.com/alinagaripova/homework-exercise1.horoscope/blob/618b438ea190399b2e6ea74b545e272c2554b765/Test/exercise1.test.js#L3-L6

**Comment by alinagaripova** [comment]
поменяла тесты на test.each, добавила travis ci и codecov.

**Comment by coursar** [comment]
Если пофиксили issue, надо закрывать сообщением коммита.
