### ISSUE TITLE
На равенство проверяем через ===

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-exercise1.horoscope#3]
https://github.com/alinagaripova/homework-exercise1.horoscope/blob/618b438ea190399b2e6ea74b545e272c2554b765/js/lib.js#L17

**Comment by alinagaripova** [comment]
исправлено

**Comment by coursar** [comment]
issue надо закрывать сообщениями коммитов, чтобы было понятно, где и когда вы что исправили
